name: Publish Package

on:
  push:
    tags:
      - 'v*'   # triggers when you push version tags

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write   # REQUIRED for OIDC

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm install

      - name: Publish
        run: npm publish